### ISSUE TITLE
Add vhead fails with google load balancer

### ISSUE THREAD

**Issue by billyfoss** [Elastifile/gcp-automation#11]
I am testing adding and removing nodes with a Google internal load balancer. 

I ran into an error where the cluster name being passed in was no longer required, but the update_vheads was still passing it. 

The error appears as
````
+ getopts 'h?:a:e:p:' opt
./update_google_ilb.sh: illegal option -- r
+ case "$opt" in
+ usage
+ cat
Usage:
  -a list of node ips
  -e service email
  -p project
  example: update_google_ilb.sh -a 10.0.0.1,10.0.0.2 -e <service account> -p <project id>
+ exit 1
````

I was able to resolve the issue by removing the "-r $CLUSTER_NAME" on line 79 of update_vheads.sh.  It was no longer needed as the update_google_ilb.sh is detecting the cluster name from the terraform show.

**Comment by elasti-guyr-zz** [comment]
Fixed, thanks Billy
