### ISSUE TITLE
var.USE_PUBLIC_IP as resource count

### ISSUE THREAD

**Issue by footprns** [Elastifile/gcp-automation#12]
There is a bug in below line. Count expect to get a number.

-----------------------
Error: Incorrect value type

  on google_ecfs.tf line 160, in resource "google_compute_instance" "Elastifile-EMS-Public":
 160:   count        = "${var.USE_PUBLIC_IP}"

Invalid expression value: number required.

Error: Invalid operand

  on google_ecfs.tf line 223, in resource "google_compute_instance" "Elastifile-EMS-Private":
 223:   count        = "${1 - var.USE_PUBLIC_IP}"
    |----------------
    | var.USE_PUBLIC_IP is false

Unsuitable value for right operand: number required.

**Comment by elasti-guyr-zz** [comment]
What did you use in the terraform.tfvar file? 
it should be true or false, for example:
USE_PUBLIC_IP = true.

Can you share your  terraform.tfvar ?

**Comment by elasti-guyr-zz** [comment]
Didn't receive a reply

**Comment by footprns** [comment]
I was running with TF ver 0.12, while the code does not support. you can close this issue
